Vagrant.configure("2") do |config|
  config.vm.box = "centos/atomic-host"

  config.vm.provider :google do |google, override|
    google.google_project_id = "hashicorp-185814"
    google.google_client_email = "boeroboy@gmail.com"
	google.google_key_location = "/home/jboero/Downloads/google-cloud-sdk/.install/.backup/platform/gsutil/third_party/oauth2client/tests/data/privatekey.p12"

    override.ssh.username = "jboero"
    override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end

end
