# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dummy.box"

  config.vm.provider :aws do |aws, override|
	aws.aws_dir = ENV['HOME'] + "/.aws/"
#	aws.access_key_id = "<YOURKEYID>"
#	aws.secret_access_key = "<YOURKEY>"
#	aws.session_token = "SESSION TOKEN"
#	aws.keypair_name = "KEYPAIR NAME"

    # CentOS 7 Atomic Host
    aws.ami = "ami-a52a34dc"

    override.ssh.username = "jboero"
    override.ssh.private_key_path = "~/.ssh/id_rsa"
  end
end
