# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.define "centos-atomic" do |catom|
	  catom.vm.hostname = "centos-atomic"
	  catom.vm.box = "centos/atomic-host"
	end
	
	config.vm.define "fedora-atomic" do |fatom|
	  fatom.vm.hostname = "fedora-atomic"
	  fatom.vm.box = "fedora/27-atomic-host"
	end
end
